### ISSUE TITLE
I broke the code somehow

### ISSUE THREAD

**Issue by nostango** [nostango/pokebot#3]
I wanted to move the code to its ideal settings (Python 3.7 and tensorflow 1.15), but I broke it in the process. I created an environment and installed Python 3.7 and tensorflow 1.15 and ran poke2.py, which is the main file for the RL Agent, but I keep getting an error that says: 
<img width="1148" alt="Screen Shot 2021-04-27 at 12 02 09 AM" src="https://user-images.githubusercontent.com/63559697/116183717-6e6c0e00-a6ec-11eb-8f6c-ff162bf1253f.png">

(Output incase the screenshot is not visible)
(poke2) alejandrovega@x86_64-apple-darwin13 agents % python3.7 poke2.py
Using TensorFlow backend.
1.15.0
WARNING:tensorflow:From /Users/alejandrovega/opt/anaconda3/envs/poke2/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "poke2.py", line 127, in <module>
    enable_double_dqn=True,
  File "/Users/alejandrovega/opt/anaconda3/envs/poke2/lib/python3.7/site-packages/rl/agents/dqn.py", line 108, in __init__
    if hasattr(model.output, '__len__') and len(model.output) > 1:
  File "/Users/alejandrovega/opt/anaconda3/envs/poke2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 741, in __len__
    "shape information.".format(self.name))
TypeError: len is not well defined for symbolic Tensors. (dense_2/BiasAdd:0) Please call `x.shape` rather than `len(x)` for shape information.

**Comment by nostango** [comment]
Fixed
